# Generated by Django 6.0 on 2025-12-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='datetime',
            new_name='release',
        ),
    ]
